# Generated by Django 4.0 on 2021-12-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_students', '0002_rename_course_student_enrol_remove_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrol',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrol',
            name='grade',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
