# Generated by Django 4.0 on 2021-12-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_students', '0003_enrol_finalized_alter_enrol_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrol',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
